# Generated by Django 5.2.7 on 2025-10-15 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='participantes',
            field=models.ManyToManyField(related_name='conversas', to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='conversa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chat.conversa', verbose_name='Conversa'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Remetente'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
