# Generated by Django 5.2.7 on 2025-10-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('H', 'Homem'), ('M', 'Mulher'), ('C_EL', 'Casal (Ele/Ela)'), ('C_EE', 'Casal (Ele/Ele)'), ('C_MM', 'Casal (Ela/Ela)'), ('T', 'Transexual'), ('CD', 'Crossdresser (CD)'), ('TV', 'Travesti'), ('GP_F', 'GP – Garota de Programa'), ('GP_M', 'GP – Garoto de Programa')], max_length=4, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero_interesse',
            field=models.CharField(blank=True, choices=[('H', 'Homens'), ('M', 'Mulheres'), ('C_EL', 'Casais (Ele/Ela)'), ('C_EE', 'Casais (Ele/Ele)'), ('C_MM', 'Casais (Ela/Ela)'), ('T', 'Transexuais'), ('CD', 'Crossdressers'), ('TV', 'Travestis'), ('GP_F', 'GPs Femininas'), ('GP_M', 'GPs Masculinos'), ('TODOS', 'Todos')], max_length=6, verbose_name='Interesse em'),
        ),
    ]
