# Generated by Django 5.2.7 on 2025-10-16 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_genero_alter_usuario_genero_interesse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fetiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Fetiche',
                'verbose_name_plural': 'Fetiches',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Interesse',
                'verbose_name_plural': 'Interesses',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento_parceiro',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento do Parceiro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_civil_parceiro',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estado Civil do Parceiro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='first_name_parceiro',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nome do Parceiro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil_parceiro',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/parceiros/', verbose_name='Foto do Parceiro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero_parceiro',
            field=models.CharField(blank=True, choices=[('H', 'Homem'), ('M', 'Mulher'), ('T', 'Transexual'), ('CD', 'Crossdresser (CD)'), ('TV', 'Travesti'), ('GP_F', 'GP – Garota de Programa'), ('GP_M', 'GP – Garoto de Programa')], max_length=4, verbose_name='Gênero do Parceiro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_name_parceiro',
            field=models.CharField(blank=True, max_length=30, verbose_name='Sobrenome do Parceiro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='orientacao_sexual',
            field=models.CharField(blank=True, max_length=50, verbose_name='Orientação Sexual'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='orientacao_sexual_parceiro',
            field=models.CharField(blank=True, max_length=50, verbose_name='Orientação Sexual do Parceiro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Profissão'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='profissao_parceiro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Profissão do Parceiro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_perfil',
            field=models.CharField(choices=[('individual', 'Individual'), ('casal_ele_ela', 'Casal (Ele/Ela)'), ('casal_ela_ela', 'Casal (Ela/Ela)'), ('casal_ele_ele', 'Casal (Ele/Ele)')], default='individual', max_length=15, verbose_name='Tipo de Perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('H', 'Homem'), ('M', 'Mulher'), ('T', 'Transexual'), ('CD', 'Crossdresser (CD)'), ('TV', 'Travesti'), ('GP_F', 'GP – Garota de Programa'), ('GP_M', 'GP – Garoto de Programa')], max_length=4, verbose_name='Gênero'),
        ),
        migrations.CreateModel(
            name='UsuarioFetiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('fetiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.fetiche')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetiches_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fetiche do Usuário',
                'verbose_name_plural': 'Fetiches dos Usuários',
                'unique_together': {('usuario', 'fetiche')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('interesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.interesse')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interesse do Usuário',
                'verbose_name_plural': 'Interesses dos Usuários',
                'unique_together': {('usuario', 'interesse')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.objetivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Objetivo do Usuário',
                'verbose_name_plural': 'Objetivos dos Usuários',
                'unique_together': {('usuario', 'objetivo')},
            },
        ),
    ]
