# Generated by Django 5.2.7 on 2025-10-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_fetiche_interesse_objetivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('H', 'Homem'), ('M', 'Mulher'), ('T', 'Transexual'), ('CD', 'Crossdresser (CD)'), ('TV', 'Travesti'), ('GP_F', 'GP Feminina'), ('GP_M', 'GP Masculina')], max_length=4, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero_parceiro',
            field=models.CharField(blank=True, choices=[('H', 'Homem'), ('M', 'Mulher'), ('T', 'Transexual'), ('CD', 'Crossdresser (CD)'), ('TV', 'Travesti'), ('GP_F', 'GP Feminina'), ('GP_M', 'GP Masculina')], max_length=4, verbose_name='Gênero do Parceiro'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_perfil',
            field=models.CharField(choices=[('', '─── PERFIL INDIVIDUAL ───'), ('individual_homem', 'Homem'), ('individual_mulher', 'Mulher'), ('individual_transexual', 'Transexual'), ('individual_crossdresser', 'Crossdresser (CD)'), ('individual_travesti', 'Travesti'), ('individual_gp_feminina', 'GP Feminina'), ('individual_gp_masculina', 'GP Masculina'), ('', '─── PERFIL CASAL ───'), ('casal_ele_ela', 'Casal (Ele/Ela)'), ('casal_ela_ela', 'Casal (Ela/Ela)'), ('casal_ele_ele', 'Casal (Ele/Ele)')], default='individual_homem', max_length=25, verbose_name='Tipo de Perfil'),
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('codigo_ibge', models.CharField(max_length=7, unique=True, verbose_name='Código IBGE')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('populacao', models.IntegerField(blank=True, null=True, verbose_name='População')),
                ('ativa', models.BooleanField(default=True, verbose_name='Cidade Ativa')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['estado', 'nome'],
                'unique_together': {('nome', 'estado')},
            },
        ),
    ]
