# Generated by Django 5.2.7 on 2025-10-16 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_add_cidade_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cidade_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.cidade', verbose_name='Cidade de Referência'),
        ),
    ]
