# Generated by Django 5.2.7 on 2025-10-16 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_add_cidade_ref_to_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRelacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Tipo de Relacionamento')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Tipo de Relacionamento',
                'verbose_name_plural': 'Tipos de Relacionamento',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='tempo_juntos',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tempo Juntos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_relacionamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.tiporelacionamento', verbose_name='Tipo de Relacionamento'),
        ),
    ]
