# Generated by Django 5.2.7 on 2025-10-16 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_tiporelacionamento_usuario_tempo_juntos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorCabelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Cor dos Cabelos')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Cor dos Cabelos',
                'verbose_name_plural': 'Cores dos Cabelos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='CorOlhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Cor dos Olhos')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Cor dos Olhos',
                'verbose_name_plural': 'Cores dos Olhos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Signo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True, verbose_name='Signo')),
                ('data_inicio', models.CharField(max_length=10, verbose_name='Data Início')),
                ('data_fim', models.CharField(max_length=10, verbose_name='Data Fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Signo',
                'verbose_name_plural': 'Signos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracoesPrivacidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_idade', models.BooleanField(default=True, verbose_name='Mostrar Idade')),
                ('mostrar_cidade', models.BooleanField(default=True, verbose_name='Mostrar Cidade')),
                ('disponivel_mensagens', models.CharField(choices=[('todos', 'Todos'), ('vips', 'Somente VIPs'), ('seguidores', 'Seguidores')], default='todos', max_length=15, verbose_name='Disponível para Mensagens')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_privacidade', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Configurações de Privacidade',
                'verbose_name_plural': 'Configurações de Privacidade',
            },
        ),
        migrations.CreateModel(
            name='EstiloVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.CharField(choices=[('principal', 'Pessoa Principal'), ('parceiro', 'Parceiro(a)')], default='principal', max_length=10, verbose_name='Pessoa')),
                ('fumante', models.CharField(choices=[('nao', 'Não'), ('sim', 'Sim'), ('ocasionalmente', 'Ocasionalmente')], default='nao', max_length=15, verbose_name='Fumante')),
                ('bebe', models.CharField(choices=[('nao', 'Não'), ('sim', 'Sim'), ('socialmente', 'Socialmente')], default='nao', max_length=15, verbose_name='Bebe')),
                ('pratica_esportes', models.CharField(choices=[('nao', 'Não'), ('sim', 'Sim'), ('as_vezes', 'Às vezes')], default='nao', max_length=15, verbose_name='Pratica Esportes')),
                ('tem_filhos', models.CharField(choices=[('nao', 'Não'), ('sim', 'Sim'), ('adultos', 'Adultos'), ('mora_com_filhos', 'Mora com filhos')], default='nao', max_length=20, verbose_name='Tem Filhos?')),
                ('tatuagens_piercings', models.CharField(choices=[('nao', 'Não'), ('sim', 'Sim'), ('varios', 'Vários')], default='nao', max_length=15, verbose_name='Possui Tatuagens ou Piercings?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estilos_vida', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Estilo de Vida',
                'verbose_name_plural': 'Estilos de Vida',
                'ordering': ['usuario', 'pessoa'],
                'unique_together': {('usuario', 'pessoa')},
            },
        ),
        migrations.CreateModel(
            name='IdentidadePreferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.CharField(choices=[('principal', 'Pessoa Principal'), ('parceiro', 'Parceiro(a)')], default='principal', max_length=10, verbose_name='Pessoa')),
                ('genero', models.CharField(blank=True, choices=[('homem', 'Homem'), ('mulher', 'Mulher'), ('trans', 'Trans'), ('outro', 'Outro')], max_length=10, verbose_name='Gênero')),
                ('orientacao_sexual', models.CharField(blank=True, choices=[('hetero', 'Hetero'), ('homo', 'Homo'), ('bi', 'Bi'), ('pan', 'Pan'), ('outro', 'Outro')], max_length=10, verbose_name='Orientação Sexual')),
                ('aberto_contatos_com', models.CharField(blank=True, choices=[('homens', 'Homens'), ('mulheres', 'Mulheres'), ('casais', 'Casais'), ('todos', 'Todos')], max_length=10, verbose_name='Aberto a novos contatos com')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identidades_preferencias', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Identidade e Preferências',
                'verbose_name_plural': 'Identidades e Preferências',
                'ordering': ['usuario', 'pessoa'],
                'unique_together': {('usuario', 'pessoa')},
            },
        ),
        migrations.CreateModel(
            name='DadosPessoaisDetalhados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.CharField(choices=[('principal', 'Pessoa Principal'), ('parceiro', 'Parceiro(a)')], default='principal', max_length=10, verbose_name='Pessoa')),
                ('nome_apelido', models.CharField(blank=True, max_length=100, verbose_name='Nome / Apelido Público')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('altura', models.PositiveIntegerField(blank=True, null=True, verbose_name='Altura (cm)')),
                ('peso', models.PositiveIntegerField(blank=True, null=True, verbose_name='Peso (kg)')),
                ('profissao_ocupacao', models.CharField(blank=True, max_length=100, verbose_name='Profissão / Ocupação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cidade_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoas_cidade_atual', to='usuarios.cidade', verbose_name='Cidade Atual')),
                ('cor_cabelos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.corcabelos', verbose_name='Cor dos Cabelos')),
                ('cor_olhos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.corolhos', verbose_name='Cor dos Olhos')),
                ('origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoas_origem', to='usuarios.cidade', verbose_name='Origem (onde nasceu)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_pessoais_detalhados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('signo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.signo', verbose_name='Signo')),
            ],
            options={
                'verbose_name': 'Dados Pessoais Detalhados',
                'verbose_name_plural': 'Dados Pessoais Detalhados',
                'ordering': ['usuario', 'pessoa'],
                'unique_together': {('usuario', 'pessoa')},
            },
        ),
    ]
