# Generated by Django 5.2.7 on 2025-10-17 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_corcabelos_corolhos_signo_configuracoesprivacidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Estado Civil')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estados Civis',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Etnia')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Etnia',
                'verbose_name_plural': 'Etnias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='NivelAbertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nível de Abertura')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Nível de Abertura',
                'verbose_name_plural': 'Níveis de Abertura',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoCorpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Tipo de Corpo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Tipo de Corpo',
                'verbose_name_plural': 'Tipos de Corpo',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilInteresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procurando_casais', models.BooleanField(default=False, verbose_name='Procurando Casais')),
                ('procurando_mulheres', models.BooleanField(default=False, verbose_name='Procurando Mulheres')),
                ('procurando_homens', models.BooleanField(default=False, verbose_name='Procurando Homens')),
                ('procurando_grupos', models.BooleanField(default=False, verbose_name='Procurando Grupos')),
                ('procurando_amizades', models.BooleanField(default=False, verbose_name='Procurando Amizades')),
                ('procurando_experiencias', models.BooleanField(default=False, verbose_name='Procurando Experiências')),
                ('objetivo_amizades', models.BooleanField(default=False, verbose_name='Objetivo: Amizades')),
                ('objetivo_relacionamento', models.BooleanField(default=False, verbose_name='Objetivo: Relacionamento')),
                ('objetivo_troca', models.BooleanField(default=False, verbose_name='Objetivo: Troca de Casais')),
                ('objetivo_aventura', models.BooleanField(default=False, verbose_name='Objetivo: Aventura')),
                ('objetivo_relacao_aberta', models.BooleanField(default=False, verbose_name='Objetivo: Relação Aberta')),
                ('objetivo_curiosidade', models.BooleanField(default=False, verbose_name='Objetivo: Curiosidade')),
                ('preferencia_romantico', models.BooleanField(default=False, verbose_name='Preferência: Romântico')),
                ('preferencia_aventureiro', models.BooleanField(default=False, verbose_name='Preferência: Aventureiro')),
                ('preferencia_intimista', models.BooleanField(default=False, verbose_name='Preferência: Intimista')),
                ('preferencia_social', models.BooleanField(default=False, verbose_name='Preferência: Social')),
                ('preferencia_privacidade', models.BooleanField(default=False, verbose_name='Preferência: Privacidade')),
                ('preferencia_publico', models.BooleanField(default=False, verbose_name='Preferência: Público')),
                ('maior_18', models.BooleanField(default=True, verbose_name='Maior de 18 anos')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nivel_abertura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.nivelabertura', verbose_name='Nível de Abertura')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_interesses', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Interesses',
                'verbose_name_plural': 'Perfis de Interesses',
            },
        ),
        migrations.CreateModel(
            name='PerfilSobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quem_somos', models.TextField(blank=True, max_length=500, verbose_name='Quem Somos')),
                ('inspiracao', models.TextField(blank=True, max_length=300, verbose_name='O que nos inspira')),
                ('frase_destaque', models.CharField(blank=True, max_length=100, verbose_name='Frase de Destaque')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('outro_link', models.URLField(blank=True, verbose_name='Outro Link')),
                ('bio_ele', models.TextField(blank=True, max_length=300, verbose_name='Bio - Ele')),
                ('bio_ela', models.TextField(blank=True, max_length=300, verbose_name='Bio - Ela')),
                ('bio_individual', models.TextField(blank=True, max_length=400, verbose_name='Bio Individual')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_sobre', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil Sobre',
                'verbose_name_plural': 'Perfis Sobre',
            },
        ),
        migrations.CreateModel(
            name='PerfilDetalhado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.CharField(choices=[('principal', 'Pessoa Principal'), ('ele', 'Ele'), ('ela', 'Ela')], default='principal', max_length=10, verbose_name='Pessoa')),
                ('nome_apelido', models.CharField(blank=True, max_length=100, verbose_name='Nome / Apelido Público')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('profissao', models.CharField(blank=True, max_length=100, verbose_name='Profissão')),
                ('altura', models.PositiveIntegerField(blank=True, null=True, verbose_name='Altura (cm)')),
                ('peso', models.PositiveIntegerField(blank=True, null=True, verbose_name='Peso (kg)')),
                ('orientacao_sexual', models.CharField(blank=True, choices=[('heterossexual', 'Heterossexual'), ('bissexual', 'Bissexual'), ('homossexual', 'Homossexual'), ('pansexual', 'Pansexual'), ('assexual', 'Assexual'), ('outro', 'Outro')], max_length=20, verbose_name='Orientação Sexual')),
                ('fumante', models.CharField(choices=[('nao', 'Não'), ('sim', 'Sim'), ('ocasionalmente', 'Ocasionalmente')], default='nao', max_length=15, verbose_name='Fumante')),
                ('bebe', models.CharField(choices=[('nao', 'Não'), ('sim', 'Sim'), ('socialmente', 'Socialmente')], default='nao', max_length=15, verbose_name='Bebe')),
                ('descricao_pessoal', models.TextField(blank=True, max_length=500, verbose_name='Descrição Pessoal')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cor_cabelos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.corcabelos', verbose_name='Cor dos Cabelos')),
                ('cor_olhos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.corolhos', verbose_name='Cor dos Olhos')),
                ('estado_civil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.estadocivil', verbose_name='Estado Civil')),
                ('etnia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.etnia', verbose_name='Etnia')),
                ('signo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.signo', verbose_name='Signo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis_detalhados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('tipo_corpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.tipocorpo', verbose_name='Tipo de Corpo')),
            ],
            options={
                'verbose_name': 'Perfil Detalhado',
                'verbose_name_plural': 'Perfis Detalhados',
                'ordering': ['usuario', 'pessoa'],
                'unique_together': {('usuario', 'pessoa')},
            },
        ),
    ]
