# Generated by Django 5.2.7 on 2025-10-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada'), ('suspensa', 'Suspensa')], default='ativa', max_length=20, verbose_name='Status')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Fim')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Cancelamento')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50, verbose_name='Método de Pagamento')),
                ('transacao_id', models.CharField(blank=True, max_length=200, verbose_name='ID da Transação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('metodo', models.CharField(choices=[('pix', 'PIX'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('boleto', 'Boleto')], max_length=20, verbose_name='Método')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('transacao_id', models.CharField(max_length=200, unique=True, verbose_name='ID da Transação')),
                ('gateway_pagamento', models.CharField(max_length=50, verbose_name='Gateway de Pagamento')),
                ('dados_transacao', models.JSONField(blank=True, null=True, verbose_name='Dados da Transação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_processamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Processamento')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PlanoAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Mensal')),
                ('preco_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Anual')),
                ('likes_ilimitados', models.BooleanField(default=False, verbose_name='Likes Ilimitados')),
                ('super_likes_diarios', models.IntegerField(default=0, verbose_name='Super Likes Diários')),
                ('boost_perfil', models.BooleanField(default=False, verbose_name='Boost de Perfil')),
                ('filtros_avancados', models.BooleanField(default=False, verbose_name='Filtros Avançados')),
                ('ver_quem_curtiu', models.BooleanField(default=False, verbose_name='Ver Quem Curtiu')),
                ('desfazer_ultimo_like', models.BooleanField(default=False, verbose_name='Desfazer Último Like')),
                ('is_ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Plano de Assinatura',
                'verbose_name_plural': 'Planos de Assinatura',
                'ordering': ['ordem', 'preco_mensal'],
            },
        ),
    ]
