# Generated by Django 5.2.7 on 2025-10-15 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='curtida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='postagem',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='postagem',
            name='curtidas',
            field=models.ManyToManyField(blank=True, related_name='postagens_curtidas', through='feed.Curtida', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curtida',
            name='postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.postagem', verbose_name='Postagem'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='feed.postagem', verbose_name='Postagem'),
        ),
        migrations.AddField(
            model_name='relacionamento',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacionamentos_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário'),
        ),
        migrations.AddField(
            model_name='relacionamento',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacionamentos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Remetente'),
        ),
        migrations.AlterUniqueTogether(
            name='curtida',
            unique_together={('usuario', 'postagem')},
        ),
        migrations.AlterUniqueTogether(
            name='relacionamento',
            unique_together={('remetente', 'destinatario')},
        ),
    ]
